CREATE TABLE IF NOT EXISTS PRODUCT(
    PRO_ID TEXT PRIMARY KEY,
    PRO_NAME TEXT,
    PRO_PRICE TEXT,
    PRO_COM TEXT
);
INSERT INTO PRODUCT(PRO_ID, PRO_NAME, PRO_PRICE, PRO_COM)VALUES
    ("101","MOTHER BOARD","3200","15"),
    ("102","KEY BOARD","450","16"),
    ("103","ZIP DRIVE","250","14"),
    ("104","SPEAKER","550","16"),
    ("105","MONITOR","5000","11");
SELECT PRO_NAME, PRO_PRICE
    FROM PRODUCT
    WHERE PRO_PRICE=(SELECT MIN(PRO_PRICE) FROM PRODUCT);
SELECT PRO_NAME, PRO_PRICE
    FROM PRODUCT
    WHERE PRO_PRICE=(SELECT MAX(PRO_PRICE) FROM PRODUCT);
